library("shiny")
library(bslib)
library("dplyr")
library("ggplot2")
library("plotly")
library("tidyverse")
library("reshape2")
source("ui.R")
source("server.R")

# Runs the application (both ui and server)
shinyApp(ui = my_ui, server = my_server)